openapi: 3.0.3

info:
  version: 1.0.0
  title: Open Trickler REST API
  description: A REST API for the Open Trickler that powers a web-based interface and mobile apps (in the future).

servers:
  - url: http://opentrickler.local/trickler/v1
  - url: http://localhost/trickler/v1

paths:
  /settings:
    get:
      summary: Read Open Trickler settings
      operationId: getSettings
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Setting'
    put:
      summary: Update Open Trickler settings
      operationId: updateSettings
      requestBody:
        description: New setting values
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Setting'
            examples:
              startTrickling:
                summary: Turn the trickler on with a set weight.
                value:
                  auto_mode: true
                  target_weight: 10.00
                  target_unit: g
              stopTrickling:
                summary: Turn the trickler off.
                value:
                  auto_mode: false
                  target_weight: 10.00
                  target_unit: g

      responses:
        '204':
          description: The settings were updated
    
components:
  schemas:
    Setting:
      type: object
      properties:
        auto_mode:
          type: boolean
        target_weight:
          type: string
          pattern: '^\d{1,3}.\d{1,3}$'
        target_unit:
          type: string
          enum:
            - g
            - gn
